services:
  app:
    image: proy-backend
    container_name: app
    depends_on:
      - dbpostgresql
    ports:
     - 3001:3001
  dbpostgresql:
    image: postgres:16-bullseye
    container_name: dbpostgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=tareaspfinal
    ports:
      - 5432:5432
  dbpostgresql_init:
    image: postgres:16-bullseye
    container_name: dbpostgresql_init
    entrypoint: ["/bin/bash", "/init.sh"]
    volumes:
      - ./db_bak/copia.backup:/copia.backup
      - ./db_bak/init.sh:/init.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tareaspfinal
      - PGPASSWORD=12345678
    depends_on:
      dbpostgresql:
        condition: service_started